import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import * as Icons from 'lucide-react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { cn } from '../lib/utils';
import Breadcrumbs from '../components/Breadcrumbs';

interface FAQItem {
  question: string;
  answer: React.ReactNode;
  schemaAnswer: string; // Plain text version for SEO schema
  category: 'General' | 'AI Capabilities' | 'Usage' | 'Technical';
}

const FAQ_DATA: FAQItem[] = [
  {
    category: 'General',
    question: "What is SEO Score?",
    answer: "SEO Score is an all-in-one, AI-powered platform designed to help website owners, marketers, and developers optimize their online presence. It provides tools for technical audits, content optimization, keyword research, and competitive analysis, all driven by advanced Google Gemini AI. Our mission is to democratize search intelligence by making professional-grade tools accessible to everyone.",
    schemaAnswer: "SEO Score is an all-in-one, AI-powered platform designed to help website owners, marketers, and developers optimize their online presence. It provides tools for technical audits, content optimization, keyword research, and competitive analysis, all driven by advanced Google Gemini AI."
  },
  {
    category: 'AI Capabilities',
    question: "How does the AI analyze my website?",
    answer: "Our platform uses Google Gemini 3.1 Pro and Flash models to simulate search engine crawler behavior and user experience. It analyzes your provided URLs or content against over 200 ranking factors, identifying patterns and providing human-like recommendations. Unlike traditional tools that use rigid rules, our AI understands context, intent, and semantic relationships.",
    schemaAnswer: "Our platform uses Google Gemini 3.1 Pro and Flash models to simulate search engine crawler behavior and user experience. It analyzes your provided URLs or content against over 200 ranking factors, identifying patterns and providing human-like recommendations."
  },
  {
    category: 'Usage',
    question: "How can I use the tools effectively?",
    answer: (
      <>
        We recommend a three-step approach: 1) Run a <Link to="/tools/free-website-seo-audit-tool" className="text-indigo-600 hover:underline font-bold">Website SEO Audit</Link> for a high-level health score. 2) Use the <Link to="/tools/free-seo-audit-checklist" className="text-indigo-600 hover:underline font-bold">SEO Audit Checklist</Link> to fix critical technical errors. 3) Use the <Link to="/tools/free-ai-content-optimization-tool" className="text-indigo-600 hover:underline font-bold">Content Optimizer</Link> and <Link to="/tools/free-keyword-research-tool" className="text-indigo-600 hover:underline font-bold">Keyword Research</Link> tools to refine your top-performing pages. Consistency is key—we suggest checking your dashboard weekly to track progress.
      </>
    ),
    schemaAnswer: "We recommend a three-step approach: 1) Run a Website SEO Audit for a high-level health score. 2) Use the SEO Audit Checklist to fix critical technical errors. 3) Use the Content Optimizer and Keyword Research tools to refine your top-performing pages."
  },
  {
    category: 'AI Capabilities',
    question: "Is the AI analysis real-time?",
    answer: (
      <>
        Yes! When you run a tool, our AI performs a live analysis based on the latest search engine guidelines and trends. For tools like the <Link to="/tools/free-website-speed-test-tool" className="text-indigo-600 hover:underline font-bold">Site Speed Checker</Link>, it simulates performance metrics to give you an immediate understanding of your site's health. This allows you to see the impact of your changes almost instantly.
      </>
    ),
    schemaAnswer: "Yes! When you run a tool, our AI performs a live analysis based on the latest search engine guidelines and trends. Our Site Speed Checker simulates performance metrics to give you an immediate understanding of your site's health."
  },
  {
    category: 'Technical',
    question: "Can I export the reports?",
    answer: "Absolutely. Every analysis report generated by SEO Score can be copied to your clipboard, printed directly, or downloaded as a professional PDF. This makes it easy to share insights with clients, team members, or developers. Our PDF reports are designed to be client-ready, with clear visualizations and actionable advice.",
    schemaAnswer: "Absolutely. Every analysis report generated by SEO Score can be copied to your clipboard, printed directly, or downloaded as a professional PDF. This makes it easy to share insights with clients, team members, or developers."
  },
  {
    category: 'General',
    question: "Is my data secure?",
    answer: "We take data privacy seriously. SEO Score primarily analyzes public-facing website data. We do not store sensitive personal information or your website's private credentials. Your analysis history is stored locally in your browser for your convenience, and we use industry-standard encryption for all data transmissions.",
    schemaAnswer: "We take data privacy seriously. SEO Score primarily analyzes public-facing website data. We do not store sensitive personal information or your website's private credentials."
  },
  {
    category: 'Technical',
    question: "Do I need to install anything on my website?",
    answer: "No installation is required. SEO Score is a cloud-based platform that analyzes your site externally, just like a search engine crawler would. You don't need to add any scripts or plugins to your website to use our tools, ensuring your site's performance remains unaffected.",
    schemaAnswer: "No installation is required. SEO Score is a cloud-based platform that analyzes your site externally, just like a search engine crawler would. No scripts or plugins needed."
  },
  {
    category: 'Usage',
    question: "Are these tools really free?",
    answer: "Yes, our core suite of SEO tools is completely free to use. We believe in democratizing SEO knowledge. While we may offer premium features or higher usage limits in the future, our goal is to ensure that every website owner has access to the essential data they need to succeed in search.",
    schemaAnswer: "Yes, our core suite of SEO tools is completely free to use. We believe in democratizing SEO knowledge and ensuring every website owner has access to essential search data."
  }
];

export default function FAQ() {
  const [expandedIndex, setExpandedIndex] = useState<number | null>(0);
  const [activeCategory, setActiveCategory] = useState<string>('All');

  const categories = ['All', ...Array.from(new Set(FAQ_DATA.map(item => item.category)))];
  
  const filteredFaqs = activeCategory === 'All' 
    ? FAQ_DATA 
    : FAQ_DATA.filter(item => item.category === activeCategory);

  const faqSchema = [
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": FAQ_DATA.map(item => ({
        "@type": "Question",
        "name": item.question,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": item.schemaAnswer
        }
      }))
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [
        {
          "@type": "ListItem",
          "position": 1,
          "name": "Dashboard",
          "item": "https://seoscore.site/"
        },
        {
          "@type": "ListItem",
          "position": 2,
          "name": "FAQ",
          "item": "https://seoscore.site/faq"
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-12 sm:py-20 transition-colors duration-300">
      <Helmet>
        <title>SEO Score FAQ | Help & Support for AI SEO Tools</title>
        <meta name="description" content="Got questions about AI SEO? Find answers on SEO Score's Gemini analysis, data security, and tool usage. Get the help you need to rank higher today." />
        <meta name="keywords" content="SEO FAQ, AI SEO help, search engine optimization questions, Google Gemini SEO analysis, SEO Score support" />
        <script type="application/ld+json">
          {JSON.stringify(faqSchema)}
        </script>
      </Helmet>

      <div className="max-w-4xl mx-auto px-4">
        <Breadcrumbs 
          className="mb-8"
          items={[{ label: 'FAQ', active: true }]} 
        />
        <div className="text-center mb-12 sm:mb-16">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="inline-flex items-center gap-2 px-3 py-1.5 sm:px-4 sm:py-2 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 rounded-full text-[10px] sm:text-xs font-black uppercase tracking-[0.2em] mb-4 sm:mb-6 border border-indigo-100 dark:border-indigo-800"
          >
            <Icons.CircleHelp size={12} className="sm:w-3.5 sm:h-3.5" />
            Support Center
          </motion.div>
          <h1 className="text-3xl sm:text-6xl font-black text-slate-900 dark:text-white tracking-tight mb-4 sm:mb-6">
            Frequently Asked <span className="text-indigo-600">Questions</span>
          </h1>
          <p className="text-base sm:text-lg text-slate-600 dark:text-slate-400 max-w-2xl mx-auto font-medium px-4">
            Everything you need to know about SEO Score and how to dominate the search rankings with AI.
          </p>
        </div>

        {/* Category Filter */}
        <div className="flex flex-wrap justify-center gap-2 mb-8 sm:mb-12">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => {
                setActiveCategory(cat);
                setExpandedIndex(null);
              }}
              className={cn(
                "px-4 py-2 sm:px-6 sm:py-2.5 rounded-full text-xs sm:text-sm font-bold transition-all border",
                activeCategory === cat
                  ? "bg-indigo-600 text-white border-indigo-600 shadow-lg shadow-indigo-200 dark:shadow-indigo-900/40"
                  : "bg-white dark:bg-slate-900 text-slate-500 dark:text-slate-400 border-slate-200 dark:border-slate-800 hover:border-indigo-300 dark:hover:border-indigo-700"
              )}
            >
              {cat}
            </button>
          ))}
        </div>

        <div className="space-y-3 sm:space-y-4">
          {filteredFaqs.map((faq, index) => {
            const isExpanded = expandedIndex === index;
            return (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.05 }}
                className={cn(
                  "bg-white dark:bg-slate-900 rounded-2xl sm:rounded-[2rem] border transition-all duration-300 overflow-hidden",
                  isExpanded 
                    ? "border-indigo-200 dark:border-indigo-800 shadow-xl shadow-indigo-100/50 dark:shadow-indigo-900/20" 
                    : "border-slate-200 dark:border-slate-800 hover:border-indigo-100 dark:hover:border-indigo-900"
                )}
              >
                <button
                  onClick={() => setExpandedIndex(isExpanded ? null : index)}
                  className="w-full px-5 sm:px-8 py-5 sm:py-6 flex items-center justify-between text-left group"
                >
                  <div className="flex items-center gap-3 sm:gap-4">
                    <div className={cn(
                      "p-2 rounded-xl transition-colors shrink-0",
                      isExpanded 
                        ? "bg-indigo-600 text-white" 
                        : "bg-slate-100 dark:bg-slate-800 text-slate-400 group-hover:text-indigo-600 dark:group-hover:text-indigo-400"
                    )}>
                      <Icons.MessageCircle size={18} className="sm:w-5 sm:h-5" />
                    </div>
                    <h3 className={cn(
                      "text-sm sm:text-lg font-bold tracking-tight transition-colors leading-tight",
                      isExpanded ? "text-slate-900 dark:text-white" : "text-slate-700 dark:text-slate-300 group-hover:text-indigo-600 dark:group-hover:text-indigo-400"
                    )}>
                      {faq.question}
                    </h3>
                  </div>
                  <motion.div
                    animate={{ rotate: isExpanded ? 180 : 0 }}
                    className={cn(
                      "text-slate-400 transition-colors shrink-0",
                      isExpanded && "text-indigo-600"
                    )}
                  >
                    <Icons.ChevronDown size={20} className="sm:w-6 sm:h-6" />
                  </motion.div>
                </button>

                <AnimatePresence>
                  {isExpanded && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: "easeInOut" }}
                    >
                      <div className="px-5 sm:px-8 pb-6 sm:pb-8 sm:pl-20">
                        <div className="text-xs sm:text-base text-slate-600 dark:text-slate-400 leading-relaxed font-medium">
                          {faq.answer}
                        </div>
                        <div className="mt-4 sm:mt-6 flex items-center gap-4">
                          <span className="text-[8px] sm:text-[10px] font-black uppercase tracking-widest text-indigo-500 bg-indigo-50 dark:bg-indigo-900/30 px-2.5 py-1 rounded-full border border-indigo-100 dark:border-indigo-800">
                            {faq.category}
                          </span>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>

        {/* CTA Section */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="mt-16 sm:mt-20 p-6 sm:p-10 bg-gradient-to-br from-indigo-600 to-purple-700 rounded-3xl sm:rounded-[3rem] text-white text-center relative overflow-hidden group shadow-2xl shadow-indigo-200 dark:shadow-none"
        >
          <div className="absolute top-0 right-0 -translate-y-1/2 translate-x-1/2 w-48 h-48 sm:w-64 sm:h-64 bg-white/10 rounded-full blur-3xl group-hover:scale-110 transition-transform duration-700" />
          <div className="relative z-10">
            <h2 className="text-2xl sm:text-3xl font-black mb-3 sm:mb-4">Still have questions?</h2>
            <p className="text-sm sm:text-lg text-indigo-100 mb-6 sm:mb-8 max-w-lg mx-auto font-medium">
              Our AI SEO expert is available 24/7 to help you with specific queries and advanced optimization strategies.
            </p>
            <Link
              to="/tools/free-ai-seo-assistant"
              className="inline-flex items-center gap-2 sm:gap-3 bg-white text-indigo-600 px-6 py-3 sm:px-8 sm:py-4 rounded-xl sm:rounded-2xl font-black uppercase tracking-widest hover:bg-indigo-50 transition-all hover:scale-105 active:scale-95 shadow-xl text-xs sm:text-base"
            >
              <Icons.MessageSquare size={18} className="sm:w-5 sm:h-5" />
              Chat with AI Expert
            </Link>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
