import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import * as Icons from 'lucide-react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { cn } from '../lib/utils';

interface FAQItem {
  question: string;
  answer: string;
  category: 'General' | 'AI Capabilities' | 'Usage' | 'Technical';
}

const FAQ_DATA: FAQItem[] = [
  {
    category: 'General',
    question: "What is SEO Score Suite?",
    answer: "SEO Score Suite is an all-in-one, AI-powered platform designed to help website owners, marketers, and developers optimize their online presence. It provides tools for technical audits, content optimization, keyword research, and competitive analysis, all driven by advanced Google Gemini AI."
  },
  {
    category: 'AI Capabilities',
    question: "How does the AI analyze my website?",
    answer: "Our platform uses Google Gemini 3.1 Pro and Flash models to simulate search engine crawler behavior and user experience. It analyzes your provided URLs or content against over 200 ranking factors, identifying patterns and providing human-like recommendations that go beyond simple rule-based checks."
  },
  {
    category: 'Usage',
    question: "How can I use the tools effectively?",
    answer: "We recommend starting with the 'Website SEO' tool for a high-level overview. From there, use the 'SEO Audit Checklist' to identify specific technical fixes, and the 'Content Optimizer' to refine your high-traffic pages. Consistency is key—regularly checking your 'SEO Dashboard' will help you track improvements over time."
  },
  {
    category: 'AI Capabilities',
    question: "Is the AI analysis real-time?",
    answer: "Yes! When you run a tool, our AI performs a live analysis based on the latest search engine guidelines and trends. For tools like the 'Site Speed Checker', it simulates performance metrics to give you an immediate understanding of your site's health without waiting for traditional crawl cycles."
  },
  {
    category: 'Technical',
    question: "Can I export the reports?",
    answer: "Absolutely. Every analysis report generated by the SEO Score Suite can be copied to your clipboard, printed directly, or downloaded as a professional PDF. This makes it easy to share insights with clients, team members, or developers."
  },
  {
    category: 'General',
    question: "Is my data secure?",
    answer: "We take data privacy seriously. SEO Score Suite analyzes public-facing website data. We do not store sensitive personal information or your website's private credentials. Your analysis history is stored locally in your browser for your convenience."
  }
];

export default function FAQ() {
  const [expandedIndex, setExpandedIndex] = useState<number | null>(0);
  const [activeCategory, setActiveCategory] = useState<string>('All');

  const categories = ['All', ...Array.from(new Set(FAQ_DATA.map(item => item.category)))];
  
  const filteredFaqs = activeCategory === 'All' 
    ? FAQ_DATA 
    : FAQ_DATA.filter(item => item.category === activeCategory);

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-12 sm:py-20 transition-colors duration-300">
      <Helmet>
        <title>FAQ | SEO Score Suite - AI-Powered SEO Insights</title>
        <meta name="description" content="Frequently asked questions about SEO Score Suite, our AI capabilities, and how to optimize your website for search engines." />
      </Helmet>

      <div className="max-w-4xl mx-auto px-4">
        <div className="text-center mb-16">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 rounded-full text-xs font-black uppercase tracking-[0.2em] mb-6 border border-indigo-100 dark:border-indigo-800"
          >
            <Icons.HelpCircle size={14} />
            Support Center
          </motion.div>
          <h1 className="text-4xl sm:text-6xl font-black text-slate-900 dark:text-white tracking-tight mb-6">
            Frequently Asked <span className="text-indigo-600">Questions</span>
          </h1>
          <p className="text-lg text-slate-600 dark:text-slate-400 max-w-2xl mx-auto font-medium">
            Everything you need to know about the SEO Score Suite and how to dominate the search rankings with AI.
          </p>
        </div>

        {/* Category Filter */}
        <div className="flex flex-wrap justify-center gap-2 mb-12">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => {
                setActiveCategory(cat);
                setExpandedIndex(null);
              }}
              className={cn(
                "px-6 py-2.5 rounded-full text-sm font-bold transition-all border",
                activeCategory === cat
                  ? "bg-indigo-600 text-white border-indigo-600 shadow-lg shadow-indigo-200 dark:shadow-indigo-900/40"
                  : "bg-white dark:bg-slate-900 text-slate-500 dark:text-slate-400 border-slate-200 dark:border-slate-800 hover:border-indigo-300 dark:hover:border-indigo-700"
              )}
            >
              {cat}
            </button>
          ))}
        </div>

        <div className="space-y-4">
          {filteredFaqs.map((faq, index) => {
            const isExpanded = expandedIndex === index;
            return (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.05 }}
                className={cn(
                  "bg-white dark:bg-slate-900 rounded-[2rem] border transition-all duration-300 overflow-hidden",
                  isExpanded 
                    ? "border-indigo-200 dark:border-indigo-800 shadow-xl shadow-indigo-100/50 dark:shadow-indigo-900/20" 
                    : "border-slate-200 dark:border-slate-800 hover:border-indigo-100 dark:hover:border-indigo-900"
                )}
              >
                <button
                  onClick={() => setExpandedIndex(isExpanded ? null : index)}
                  className="w-full px-8 py-6 flex items-center justify-between text-left group"
                >
                  <div className="flex items-center gap-4">
                    <div className={cn(
                      "p-2 rounded-xl transition-colors",
                      isExpanded 
                        ? "bg-indigo-600 text-white" 
                        : "bg-slate-100 dark:bg-slate-800 text-slate-400 group-hover:text-indigo-600 dark:group-hover:text-indigo-400"
                    )}>
                      <Icons.MessageCircle size={20} />
                    </div>
                    <span className={cn(
                      "text-lg font-bold tracking-tight transition-colors",
                      isExpanded ? "text-slate-900 dark:text-white" : "text-slate-700 dark:text-slate-300 group-hover:text-indigo-600 dark:group-hover:text-indigo-400"
                    )}>
                      {faq.question}
                    </span>
                  </div>
                  <motion.div
                    animate={{ rotate: isExpanded ? 180 : 0 }}
                    className={cn(
                      "text-slate-400 transition-colors",
                      isExpanded && "text-indigo-600"
                    )}
                  >
                    <Icons.ChevronDown size={24} />
                  </motion.div>
                </button>

                <AnimatePresence>
                  {isExpanded && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: "easeInOut" }}
                    >
                      <div className="px-8 pb-8 pl-20">
                        <p className="text-slate-600 dark:text-slate-400 leading-relaxed font-medium">
                          {faq.answer}
                        </p>
                        <div className="mt-6 flex items-center gap-4">
                          <span className="text-[10px] font-black uppercase tracking-widest text-indigo-500 bg-indigo-50 dark:bg-indigo-900/30 px-3 py-1 rounded-full border border-indigo-100 dark:border-indigo-800">
                            {faq.category}
                          </span>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>

        {/* CTA Section */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="mt-20 p-10 bg-gradient-to-br from-indigo-600 to-purple-700 rounded-[3rem] text-white text-center relative overflow-hidden group shadow-2xl shadow-indigo-200 dark:shadow-none"
        >
          <div className="absolute top-0 right-0 -translate-y-1/2 translate-x-1/2 w-64 h-64 bg-white/10 rounded-full blur-3xl group-hover:scale-110 transition-transform duration-700" />
          <div className="relative z-10">
            <h2 className="text-3xl font-black mb-4">Still have questions?</h2>
            <p className="text-indigo-100 mb-8 max-w-lg mx-auto font-medium">
              Our AI SEO expert is available 24/7 to help you with specific queries and advanced optimization strategies.
            </p>
            <Link
              to="/tool/seo-chat"
              className="inline-flex items-center gap-3 bg-white text-indigo-600 px-8 py-4 rounded-2xl font-black uppercase tracking-widest hover:bg-indigo-50 transition-all hover:scale-105 active:scale-95 shadow-xl"
            >
              <Icons.MessageSquare size={20} />
              Chat with AI Expert
            </Link>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
